name: Manual AOT build

on:
  workflow_dispatch:

jobs:
  manual-aot:
    name: AOT manual build
    runs-on: windows-latest
    strategy:
      matrix:
        os: [win]
        arch: [x64]
        mode: [aot]
        optimization: ['size']
    env:
      BUILD_NAME: ${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}-${{ matrix.optimization }}
      BUILD_PATH: ${{ github.workspace }}/${{ github.event.repository.name }}/bin/${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}-${{ matrix.optimization }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add MSBUILD to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: |
            ~\.nuget\packages
            ${{ github.workspace }}\${{ github.event.repository.name }}\obj
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Dotnet build
        run: dotnet publish ${{ github.workspace }}/${{ github.event.repository.name }}/${{ github.event.repository.name }}.csproj `
              --no-restore `
              --no-build `
              /p:PublishDir=${{ env.BUILD_PATH }} `
              /p:PlatformTarget=${{ matrix.arch }} `
              /p:RuntimeIdentifier=${{ matrix.os }}-${{ matrix.arch }} `
              /p:OptimizationPreference=${{ matrix.optimization }} `
              /p:PublishAot=true

      - name: Archive build
        run: Compress-Archive `
              -Path ${{ env.BUILD_PATH }} `
              -DestinationPath "${{ env.BUILD_PATH }}.zip"
