# Perform dotnet build on every push event

name: Build

on: push

jobs:
  build-jit:
    name: JIT build
    runs-on: windows-latest
    strategy:
      matrix:
        os: [win]
        arch: [x86, x64, arm64]
        mode: [jit]
        single-file: [false, true]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-dependency-path: './${{ github.event.repository.name }}/packages.lock.json'

      - name: Restore dependencies
        run: dotnet restore './${{ github.event.repository.name }}/${{ github.event.repository.name }}.csproj' --locked-mode --force-evaluate

      - name: Dotnet build
        run: dotnet build ${{ github.workspace }}/${{ github.event.repository.name }}/${{ github.event.repository.name }}.csproj `
              /p:PlatformTarget=${{ matrix.arch }} `
              /p:RuntimeIdentifier=${{ matrix.os }}-${{ matrix.arch }} `
              /p:PublishSingleFile=${{ matrix.single-file }}

  build-aot:
    name: AOT build
    strategy:
      matrix:
        os: [win]
        arch: [x64]
        mode: [aot]
        optimization: ['speed', 'size']
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-dependency-path: './${{ github.event.repository.name }}/packages.lock.json'

      - name: Restore dependencies
        run: dotnet restore './${{ github.event.repository.name }}/${{ github.event.repository.name }}.csproj' --locked-mode --force-evaluate

      - name: Dotnet build
        run: dotnet build ${{ github.workspace }}/${{ github.event.repository.name }}/${{ github.event.repository.name }}.csproj `
              /p:PlatformTarget=${{ matrix.arch }} `
              /p:RuntimeIdentifier=${{ matrix.os }}-${{ matrix.arch }} `
              /p:OptimizationPreference=${{ matrix.optimization }} `
              /p:PublishAot=true
