name: Test PR labels

on:
  pull_request:
    types: 
      - closed
      - reopened
    branches:
      - main

jobs:
  pr-labels:
    runs-on: ubuntu-latest

    # if: github.event.pull_request.merged

    steps:
      # - name: Show PR number
      #   run: echo "${{ github.event.pull_request.number }}"
      # - name: Show PR labels
      #   run: echo "${{ toJson(github.event.pull_request.labels) }}"

      # - name: Check if any label contains "minor"
      #   if: contains(join(github.event.pull_request.labels.*.name, ' '), 'minor')
      #   run: echo "Found a label containing 'minor'!"
      # - name: Labels did not contain "minor"
      #   if: ${{ !contains(join(github.event.pull_request.labels.*.name, ' '), 'minor') }}
      #   run: echo "No label containing 'minor' found."

      - name: Generate SemVer tag
        id: gen_tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
          release_strategy: none
          tag_format: "v%major%.%minor%.%patch%"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print SemVer tag
        run: echo "${{ steps.gen_tag.outputs.tag }}"
