# This workflow will build and publish a WinUI 3 unpackaged desktop application
# built on .NET.

name: WinUI 3 app publish

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        os: [win]
        arch: [x64]

    runs-on: windows-latest

    env:
      Project_Name: BlankAppPublishDemo

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core Runtime
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Run dotnet publish
      run: cd ${{ env.Project_Name }} && dotnet publish ${{ env.Project_Name }}.csproj /p:Configuration=Release /p:PlatformTarget=${{ matrix.arch }} /p:PublishProfile=${{ matrix.os }}-${{ matrix.arch }}

    - name: Upload app
      uses: actions/upload-artifact@v4
      with:
        name: App-net8.0-windows10.0.19041.0-${{ matrix.os }}-${{ matrix.arch }}
        path: ${{ env.Project_Name }}/bin/Release/net8.0-windows10.0.19041.0/${{ matrix.os }}-${{ matrix.arch }}/publish
        if-no-files-found: error
        compression-level: 9
        overwrite: true
