# This workflow will build and publish a WinUI 3 unpackaged desktop application
# built on .NET.

name: Build and Publish WinUI 3 App

on:
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        configuration: [Release]
        os: [win]
        arch: [x86, x64, arm64]
        aot: ['', 'speed', 'size']
        # profiles:
        #   - win-x86
        #   - win-x64
        #   - win-x64-aot-speed
        #   - win-x64-aot-size
        #   - win-arm64
        #   - win-arm64-aot-speed
        #   - win-arm64-aot-size

    runs-on: windows-latest

    env:
      project_name: BlankAppPublishDemo

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Run dotnet publish
      # run: cd ${{ env.project_name }} && dotnet publish ${{ env.project_name }}.csproj /p:Configuration=${{ env.configuration }} /p:PlatformTarget=${{ matrix.arch }} /p:PublishProfile=${{ matrix.os }}-${{ matrix.arch }}
      run: |
        cd ${{ env.project_name }}
        dotnet publish ${{ env.project_name }}.csproj `
          /p:Configuration=${{ matrix.configuration }} `
          /p:PlatformTarget=${{ matrix.arch }} `
          /p:PublishProfile=${{ matrix.os }}-${{ matrix.arch }}${{ (matrix.arch == 'x64' || matrix.arch == 'arm64') && matrix.aot != '' && format('-aot-{0}', matrix.aot) || '' }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.project_name }}-${{ matrix.os }}-${{ matrix.arch }}
        path: ${{ github.workspace }}/${{ env.project_name }}/bin/${{ matrix.os }}-${{ matrix.arch }}/publish/${{ env.project_name }}.exe
        if-no-files-found: error
        compression-level: 9
        overwrite: true
