name: Build and Publish WinUI 3 App

on:
  push:
    tags:
      - "v*"

env:
  project_name: BlankAppPublishDemo

jobs:
  build-jit:
    name: Build JIT artifacts 
    strategy:
      matrix:
        os: [win]
        arch: [x86, x64, arm64]
        profile: [jit]
        single-file: [false, true]
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBUILD to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Dotnet build
      run: |
        cd ${{ env.project_name }}
        dotnet publish ${{ env.project_name }}.csproj `
          /p:PublishProfile=${{ matrix.profile }} `
          /p:PlatformTarget=${{ matrix.arch }} `
          /p:RuntimeIdentifier=${{ matrix.os }}-${{ matrix.arch }} `
          /p:PublishSingleFile=${{ matrix.single-file }}

    - name: Archive build result
      run: |
        Compress-Archive `
          -Path ${{ github.workspace }}/${{ env.project_name }}/bin/${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.profile }}${{ matrix.single-file && '-single-file' || '' }} `
          -DestinationPath "${{ github.workspace }}/${{ env.project_name }}/bin/${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.profile }}${{ matrix.single-file && '-single-file' || '' }}.zip"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.project_name }}-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.profile }}${{ matrix.single-file && '-single-file' || '' }}
        path: "${{ github.workspace }}/${{ env.project_name }}/bin/${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.profile }}${{ matrix.single-file && '-single-file' || '' }}.zip"
        if-no-files-found: error
        compression-level: 0 # since only transferred between the jobs
        overwrite: true


  build-aot:
    name: Build AOT artifacts
    strategy:
      matrix:
        os: [win]
        arch: [x64]
        profile: [aot]
        optimization: ['speed', 'size']
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBUILD to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Dotnet build
      run: |
        cd ${{ env.project_name }}
        dotnet publish ${{ env.project_name }}.csproj `
          /p:PublishProfile=${{ matrix.profile }} `
          /p:PlatformTarget=${{ matrix.arch }} `
          /p:RuntimeIdentifier=${{ matrix.os }}-${{ matrix.arch }} `
          /p:OptimizationPreference=${{ matrix.optimization }}

    - name: Archive build result
      run: |
        Compress-Archive `
          -Path ${{ github.workspace }}/${{ env.project_name }}/bin/${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.profile }}-${{ matrix.optimization }} `
          -DestinationPath "${{ github.workspace }}/${{ env.project_name }}/bin/${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.profile }}-${{ matrix.optimization }}.zip"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.project_name }}-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.profile }}-${{ matrix.optimization }}
        path: "${{ github.workspace }}/${{ env.project_name }}/bin/${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.profile }}-${{ matrix.optimization }}.zip"
        if-no-files-found: error
        compression-level: 0 # since only transferred between the jobs
        overwrite: true

  
  release-github:
    name: Publish GitHub release
    needs: [build-jit, build-aot]
    runs-on: windows-latest

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ env.project_name }}-*
          path: ./artifacts

      - name: List all downloaded artifacts
        run: Get-ChildItem -Recurse -Path ./artifacts

      # Workaround for: https://github.com/actions/download-artifact/issues/374
      # - name: Zip artifacts
      #   run: |
      #     cd ${{ env.project_name }}/bin
      #     Compress-Archive -Path "${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.profile }}${{ matrix.single-file && '-single-file' || '' }}" -DestinationPath "${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.profile }}${{ matrix.single-file && '-single-file' || '' }}.zip"

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/${{ env.project_name }}-*.zip
          overwrite_files: true
          fail_on_unmatched_files: true
          make_latest: true
          prerelease: false
          draft: false
