name: Manual Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        id: gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          
      - name: Checkout code
        if: ${{ steps.gpg.outputs.keyid != null }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup git credentials
        if: ${{ steps.gpg.outputs.keyid != null }}
        shell: bash
        run: |
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER_NAME }}"

      - name: Get latest tag
        if: ${{ steps.gpg.outputs.keyid != null }}
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Bump tag
        if: ${{ steps.get-latest-tag.outputs.tag != null }}
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: patch
          
      - name: Create new tag
        if: ${{ steps.bump-semver.outputs.new_version != null }}
        shell: bash
        run: |
          tag=${{ steps.bump-semver.outputs.new_version }}
          keyid=${{ steps.gpg.outputs.keyid }}
          git tag -u ${keyid} "${tag}" -m "Release ${tag}"
        
      - name: Push tag
        if: ${{ steps.bump-semver.outputs.new_version != null }}
        shell: bash
        run: |
          tag=${{ steps.bump-semver.outputs.new_version }}
          git push origin "${tag}"
